import Head from 'next/head';
import {
  FunctionComponent,
  PropsWithChildren,
} from 'react';
import { Footer, Navbar } from '@components/common';

type Props = {
  pageTitle: string;
};

const PageLayout: FunctionComponent<
  PropsWithChildren<Props>
> = ({ children, pageTitle }) => {
  return (
    <>
      <div className='px-4 pb-8 mx-auto space-y-8 page-layout max-w-7xl sm:px-6 lg:px-8'>
        <Head>
          <title>{pageTitle}</title>
          <meta
            name='description'
            content='Generated by create next app'
          />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <div className='relative pb-8 bg-white lg:w-full lg:max-w-2xl'>
          <Navbar />
        </div>
        <div className='max-w-2xl px-4 mx-auto lg:max-w-7xl'>
          {children}
        </div>
      </div>
      <Footer />
    </>
  );
};

export default PageLayout;
