import Head from 'next/head';
import { FunctionComponent, PropsWithChildren } from 'react';
import { Footer, Navbar } from '../../common';

const PageLayout: FunctionComponent<PropsWithChildren> = ({ children }) => {
  return (
    <>
      <div className='px-4 mx-auto space-y-8 max-w-7xl sm:px-6 lg:px-8'>
        <Head>
          <title>Portfolio - Filip Jerga</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <div className='relative pb-8 bg-white lg:w-full lg:max-w-2xl'>
          <Navbar />
        </div>
        <div className='max-w-2xl px-4 mx-auto lg:max-w-7xl'>{children}</div>
      </div>
      <Footer />
    </>
  );
};

export default PageLayout;
