import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Personal App - Joshua Torres</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 className="m-2 text-4xl font-bold text-cyan-500">With Tailwind CSS</h1>
    </>
  );
}
