import Head from 'next/head';
import Image from 'next/legacy/image';
import React, { FunctionComponent, PropsWithChildren } from 'react';

import { Navbar, Header, Footer } from '../../common';

const BaseLayout: FunctionComponent<PropsWithChildren> = ({ children }) => {
  return (
    <>
      <div className='px-4 mx-auto space-y-8 max-w-7xl sm:px-6 lg:px-8'>
        <Head>
          <title>Portfolio - Joshua Torres</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <div className='relative'>
          <div className='relative z-10 pb-8 bg-white sm:pb-16 md:pb-20 lg:w-full lg:max-w-2xl lg:pb-28 xl:pb-32'>
            <Navbar />
            <Header />
          </div>
          <div className='relative lg:absolute lg:inset-y-0 lg:right-0 lg:w-1/2'>
            <Image
              priority
              layout='fill'
              alt=''
              className='object-cover w-full h-56 sm:h-72 md:h-96 lg:h-full lg:w-full'
              src='https://images.unsplash.com/photo-1461749280684-dccba630e2f6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1369&q=60'
            />
          </div>
        </div>

        <div className='max-w-2xl px-4 py-16 mx-auto sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8'>
          {children}
        </div>
      </div>
      <Footer />
    </>
  );
};

export default BaseLayout;
